# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82aada0520ba59b43fadef236c3dda6b"
name = "B2B Quote Manager"
application_url = "https://94e269b874d6.ngrok-free.app/"
embedded = true
handle = "b2b-quote-manager"

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://94e269b874d6.ngrok-free.app/auth/callback",
  "https://94e269b874d6.ngrok-free.app/auth/shopify/callback",
  "https://94e269b874d6.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[access_scopes]
scopes = "read_draft_orders,write_draft_orders,read_customers,write_customers,read_products,write_payment_terms"

